---
kind: Service
apiVersion: v1
metadata:
  labels:
    service: mongo
    app: selinon-storages
    component: mongo
  name: mongo
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    service: mongo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: mogno
    app: selinon-storages
    component: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      service: mongo
  template:
    metadata:
      labels:
        service: mongo
    spec:
      containers:
      - env:
        - name: MONGODB_USER
          valueFrom:
            configMapKeyRef:
              name: selinon
              key: mongo-user
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: selinon
              key: mongo-password
        - name: MONGODB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: selinon
              key: mongo-database
        - name: MONGODB_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: selinon
              key: mongo-admin-password
        name: mongo
        # image: 'mongo:2.4'
        image: 'arm64v8/mongo:6.0'
        ports:
          - containerPort: 27017
            protocol: TCP
        resources:
          requests:
            memory: "128Mi"
            cpu: "125m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        readinessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 5
          periodSeconds: 60
          timeoutSeconds: 10
        volumeMounts:
          - mountPath: /var/lib/mongodb/data/
            name: mongo-volume
      volumes:
      - name: mongo-volume
        emptyDir: {}
