---
kind: Service
apiVersion: v1
metadata:
  labels:
    service: mongo-express
    app: selinon-storages
    component: mongo-express
  name: mongo-express
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8081
  selector:
    service: mongo-express
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: mongo-express
    app: selinon-storages
    component: mongo-express
  name: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      service: mongo-express
  template:
    metadata:
      labels:
        service: mongo-express
    spec:
      containers:
      - env:
        - name: ME_CONFIG_MONGODB_ENABLE_ADMIN
          value: 'false'
        - name: ME_CONFIG_MONGODB_AUTH_USERNAME
          valueFrom:
            configMapKeyRef:
              name: selinon
              key: mongo-user
        - name: ME_CONFIG_MONGODB_AUTH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: selinon
              key: mongo-password
        - name: ME_CONFIG_MONGODB_AUTH_DATABASE
          valueFrom:
            configMapKeyRef:
              name: selinon
              key: mongo-database
        name: mongo-express
        # image: 'mongo-express:0.45.0'
        image: 'arm64v8/mongo-express:0.54.0'
        ports:
          - containerPort: 8081
            protocol: TCP
        resources:
          requests:
            memory: "128Mi"
            cpu: "125m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: '/'
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 10
        livenessProbe:
          httpGet:
            path: '/'
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 60
          timeoutSeconds: 10
